spring:
    application:
        name: ruleEngine_server
    config:
        import: optional:file:.env[.properties]

    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}
            database: ${REDIS_DATABASE}

    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

eureka:
    client:
        enabled: false

mqtt:
    enabled: true
    broker-url: ${MQTT_BROKER_URL}
    client-id: ${MQTT_CLIENT_ID}
    username: ${MQTT_USERNAME:}
    password: ${MQTT_PASSWORD:}
    subscribe-topics: "mushroom/#, application/#"

custom-rabbitmq:
    queue:
        threshold-info: "yes-nhn.rule-engine.threshold-info.queue"
        sensor-info: "yes-nhn.rule-engine.sensor-info.queue"
        notification-threshold: "yes-nhn.notification.threshold.queue"
    exchange:
        from-cultivation: "yes-nhn.sensor.exchange"
        to-notification : "yes-nhn.notification.exchange"

influx:
    url: ${INFLUX_URL}
    org: ${INFLUX_ORG}
    bucket: ${INFLUX_BUCKET:sensor-data}
    token: ${INFLUX_TOKEN}
    cloudflare:
        access-client-id: ${CF_ACCESS_CLIENT_ID:}
        access-client-secret: ${CF_ACCESS_CLIENT_SECRET:}

rule-engine:
    alert:
        cooldown:
            minutes: 10

logging:
    level:
        site.yesaido.ruleengine_server: debug