spring:
    application:
        name: ruleEngine_server
    config:
        import: optional:file:.env[.properties]
    profiles:
        active: dev

    data:
        redis:
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}
            database: ${REDIS_DATABASE}

    rabbitmq:
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

mqtt:
    client-id: ${MQTT_CLIENT_ID}
    username: ${MQTT_USERNAME}
    password: ${MQTT_PASSWORD}
    subscribe-topics: ${MQTT_SUBSCRIBE_TOPICS}

custom-rabbitmq:
    queue:
        # todo : 작명 규칙 논의에 따른 큐 이름 변경
        cultivation-info: "mushmush.cultivation-info.queue"
        sensor-info: "mushmush.sensor-info.queue"