spring:
    application:
        name: ruleEngine_server
    config:
        import: optional:file:.env[.properties]

    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}
            database: ${REDIS_DATABASE}

    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

eureka:
    client:
        enabled: false

mqtt:
    broker-url: ${MQTT_BROKER_URL}
    client-id: ${MQTT_CLIENT_ID}
#    username: ${MQTT_USERNAME}
#    password: ${MQTT_PASSWORD}
    subscribe-topics: "mushroom/#, application/#"

custom-rabbitmq:
    queue:
        # todo : 작명 규칙 논의에 따른 큐 이름 변경
        cultivation-info: "mushmush.cultivation-info.queue"
        sensor-info: "mushmush.sensor-info.queue"

logging:
    level:
        site.yesaido.ruleengine_server: debug